package:
  name: bouncycastle-fips
  version: 2.1.1
  epoch: 2
  description: "Bouncy Castle Provider"
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/${{package.version}}/bc-fips-${{package.version}}.jar
      extract: false
      expected-sha256: a430d935ad6cec6d045930758457740f5a5f8f9715894e347f6800f7926a7321

  - name: install
    runs: |
      mv bc-fips-${{package.version}}.jar bc-fips.jar
      install -Dm644 -t "${{targets.destdir}}"/usr/share/java/bouncycastle-fips bc-fips.jar

test:
  environment:
    contents:
      packages:
        - openjdk-21-default-jvm
  pipeline:
    - name: Verify Bouncy Castle FIPS Provider
      runs: |
        env CLASSPATH="/usr/share/java/bouncycastle-fips/*:./*:." \
        java org.bouncycastle.util.DumpInfo
