package:
  name: ghup
  version: 0.15.0
  epoch: 0
  description: A tool for managing GitHub repository tags and content from third-party automation systems
  copyright:
    - license: BSD-3-Clause

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nexthink-oss/ghup
      tag: v${{package.version}}
      expected-commit: faa1c7b13b87d1dbcd0601307b8551836da39699

  - uses: go/build
    with:
      packages: .
      ldflags: >-
        -X main.version=${{package.version}}
        -X main.commit=$(git rev-parse HEAD)
        -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
      output: ghup

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: nexthink-oss/ghup

test:
  pipeline:
    - name: Test ghup version command
      runs: |
        # Check the version of ghup
        ghup --version
